.TH SECRET 1
.SH NAME
secret \- transfer encrypted files over network hidden inside ICMP ECHO_REQUEST/RESPONSE messages
.SH SYNOPSIS
.B secret
\fB\-r\fR \fIfile\fR
\fB\-s\fR \fIip|hostname\fR
[\fB\-l\fR]
[\fB\-v\fR]
[\fB\-h\fR]
.SH DESCRIPTION
.B secret
is a client/server application, that uses ICMP ECHO_REQUEST and ECHO_RESPONSE packets to transfer files discreetly over the network,
while using the AES cipher for file encryption. It uses a secret protocol, which uses the first 8 bytes in the ICMP data field
for client/server signature, client's current assigned ID and sequence number of the file data packet. The rest is usually filled with the encrypted file data.
.PP
The client sends the file size and file name to the server, which confirms start of the transmission while assigning the client an available ID.
The server then starts receiving individual file data packets from client, which he has to either confirm, or ask for resend if the data arrived corrupted.
The server can serve up to \fBMAX_CLIENT_ID\fR (set to 32 by default) clients at any single time instance.
The file is saved in the same directory the server is running from.
.PP
.B secret
supports only IPv4 protocol, IPv6 is not supported.
.PP
.B secret
needs to be run with root privileges to function properly.
.SH OPTIONS
.TP
.BR \-r " " \fIfile\fR
Select the file to be sent (supports both relative and absolute path).
.TP
.BR \-s " " \fIip|hostname\fR
Select IPv4 address or hostname of the receiving server.
.TP
.BR \-l
Run the program in listen (server) mode.
.TP
.BR \-v
Enable printing useful program and file transfer status information to the standard output (verbose).
.TP
.BR \-h
Show program information and correct usage (help).
.SH EXAMPLES
.SS Run as client
secret \-r example_file \-s 127.0.0.1
.PP
secret \-r ../my_dir/cat.jpg \-s merlin.fit.vutbr.cz -v
.SS Run as server
secret \-l
.SS Show help
secret \-h
.SH FILES
.I ./secret.cpp
.PP
.I ./secret.hpp
.PP
.I ./Makefile
.PP
.I ./secret.1
.PP
.I ./manual.pdf